Cleaned up some whitespace

diff --git a/scorched/missing b/scorched/missing
--- a/scorched/missing
+++ b/scorched/missing
@@ -103,8 +103,8 @@ WARNING: \`$1' is missing on your system.  You should only need it if
 
   autoconf)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+      # We have it, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
@@ -117,8 +117,8 @@ WARNING: \`$1' is missing on your system.  You should only need it if
 
   autoheader)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+      # We have it, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
@@ -132,7 +132,7 @@ WARNING: \`$1' is missing on your system.  You should only need it if
     for f in $files; do
       case "$f" in
       *:*) touch_files="$touch_files "`echo "$f" |
-				       sed -e 's/^[^:]*://' -e 's/:.*//'`;;
+                       sed -e 's/^[^:]*://' -e 's/:.*//'`;;
       *) touch_files="$touch_files $f.in";;
       esac
     done
@@ -141,8 +141,8 @@ WARNING: \`$1' is missing on your system.  You should only need it if
 
   automake*)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+      # We have it, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
@@ -151,14 +151,14 @@ WARNING: \`$1' is missing on your system.  You should only need it if
          You might want to install the \`Automake' and \`Perl' packages.
          Grab them from any GNU archive site."
     find . -type f -name Makefile.am -print |
-	   sed 's/\.am$/.in/' |
-	   while read f; do touch "$f"; done
+      sed 's/\.am$/.in/' |
+      while read f; do touch "$f"; done
     ;;
 
   autom4te)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+      # We have it, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
@@ -171,15 +171,15 @@ WARNING: \`$1' is needed, and you do not seem to have it handy on your
     file=`echo "$*" | sed -n 's/.*--output[ =]*\([^ ]*\).*/\1/p'`
     test -z "$file" && file=`echo "$*" | sed -n 's/.*-o[ ]*\([^ ]*\).*/\1/p'`
     if test -f "$file"; then
-	touch $file
+      touch $file
     else
-	test -z "$file" || exec >$file
-	echo "#! /bin/sh"
-	echo "# Created by GNU Automake missing as a replacement of"
-	echo "#  $ $@"
-	echo "exit 0"
-	chmod +x $file
-	exit 1
+      test -z "$file" || exec >$file
+      echo "#! /bin/sh"
+      echo "# Created by GNU Automake missing as a replacement of"
+      echo "#  $ $@"
+      echo "exit 0"
+      chmod +x $file
+      exit 1
     fi
     ;;
 
@@ -191,25 +191,25 @@ WARNING: \`$1' is missing on your system.  You should only need it if
          \`Bison' from any GNU archive site."
     rm -f y.tab.c y.tab.h
     if [ $# -ne 1 ]; then
-        eval LASTARG="\${$#}"
-	case "$LASTARG" in
-	*.y)
-	    SRCFILE=`echo "$LASTARG" | sed 's/y$/c/'`
-	    if [ -f "$SRCFILE" ]; then
-	         cp "$SRCFILE" y.tab.c
-	    fi
-	    SRCFILE=`echo "$LASTARG" | sed 's/y$/h/'`
-	    if [ -f "$SRCFILE" ]; then
-	         cp "$SRCFILE" y.tab.h
-	    fi
-	  ;;
-	esac
+      eval LASTARG="\${$#}"
+      case "$LASTARG" in
+      *.y)
+        SRCFILE=`echo "$LASTARG" | sed 's/y$/c/'`
+        if [ -f "$SRCFILE" ]; then
+             cp "$SRCFILE" y.tab.c
+        fi
+        SRCFILE=`echo "$LASTARG" | sed 's/y$/h/'`
+        if [ -f "$SRCFILE" ]; then
+             cp "$SRCFILE" y.tab.h
+        fi
+        ;;
+      esac
     fi
     if [ ! -f y.tab.h ]; then
-	echo >y.tab.h
+      echo >y.tab.h
     fi
     if [ ! -f y.tab.c ]; then
-	echo 'main() { return 0; }' >y.tab.c
+      echo 'main() { return 0; }' >y.tab.c
     fi
     ;;
 
@@ -221,50 +221,50 @@ WARNING: \`$1' is missing on your system.  You should only need it if
          \`Flex' from any GNU archive site."
     rm -f lex.yy.c
     if [ $# -ne 1 ]; then
-        eval LASTARG="\${$#}"
-	case "$LASTARG" in
-	*.l)
-	    SRCFILE=`echo "$LASTARG" | sed 's/l$/c/'`
-	    if [ -f "$SRCFILE" ]; then
-	         cp "$SRCFILE" lex.yy.c
-	    fi
-	  ;;
-	esac
+      eval LASTARG="\${$#}"
+      case "$LASTARG" in
+      *.l)
+        SRCFILE=`echo "$LASTARG" | sed 's/l$/c/'`
+        if [ -f "$SRCFILE" ]; then
+             cp "$SRCFILE" lex.yy.c
+        fi
+        ;;
+      esac
     fi
     if [ ! -f lex.yy.c ]; then
-	echo 'main() { return 0; }' >lex.yy.c
+      echo 'main() { return 0; }' >lex.yy.c
     fi
     ;;
 
   help2man)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+      # We have it, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
 WARNING: \`$1' is missing on your system.  You should only need it if
-	 you modified a dependency of a manual page.  You may need the
-	 \`Help2man' package in order for those modifications to take
-	 effect.  You can get \`Help2man' from any GNU archive site."
+         you modified a dependency of a manual page.  You may need the
+         \`Help2man' package in order for those modifications to take
+         effect.  You can get \`Help2man' from any GNU archive site."
 
     file=`echo "$*" | sed -n 's/.*-o \([^ ]*\).*/\1/p'`
     if test -z "$file"; then
-	file=`echo "$*" | sed -n 's/.*--output=\([^ ]*\).*/\1/p'`
+      file=`echo "$*" | sed -n 's/.*--output=\([^ ]*\).*/\1/p'`
     fi
     if [ -f "$file" ]; then
-	touch $file
+      touch $file
     else
-	test -z "$file" || exec >$file
-	echo ".ab help2man is required to generate this page"
-	exit 1
+      test -z "$file" || exec >$file
+      echo ".ab help2man is required to generate this page"
+      exit 1
     fi
     ;;
 
   makeinfo)
     if test -z "$run" && (makeinfo --version) > /dev/null 2>&1; then
-       # We have makeinfo, but it failed.
-       exit 1
+      # We have makeinfo, but it failed.
+      exit 1
     fi
 
     echo 1>&2 "\
@@ -293,25 +293,25 @@ WARNING: \`$1' is missing on your system.  You should only need it if
     # Look for gnutar/gtar before invocation to avoid ugly error
     # messages.
     if (gnutar --version > /dev/null 2>&1); then
-       gnutar "$@" && exit 0
+      gnutar "$@" && exit 0
     fi
     if (gtar --version > /dev/null 2>&1); then
-       gtar "$@" && exit 0
+      gtar "$@" && exit 0
     fi
     firstarg="$1"
     if shift; then
-	case "$firstarg" in
-	*o*)
-	    firstarg=`echo "$firstarg" | sed s/o//`
-	    tar "$firstarg" "$@" && exit 0
-	    ;;
-	esac
-	case "$firstarg" in
-	*h*)
-	    firstarg=`echo "$firstarg" | sed s/h//`
-	    tar "$firstarg" "$@" && exit 0
-	    ;;
-	esac
+      case "$firstarg" in
+      *o*)
+        firstarg=`echo "$firstarg" | sed s/o//`
+        tar "$firstarg" "$@" && exit 0
+        ;;
+      esac
+      case "$firstarg" in
+      *h*)
+        firstarg=`echo "$firstarg" | sed s/h//`
+        tar "$firstarg" "$@" && exit 0
+        ;;
+      esac
     fi
 
     echo 1>&2 "\
